baseURL = "https://lambdajunkie.org/"
baseurl      = "localhost"
title        = "lambdajunkie"
languageCode = "en-us"
theme        = "hello-friend-ng"

[pagination]
    pagerSize     = 10
[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # "light" or "dark"
  theme = "light"
  enableThemeToggle=true

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5

  # Show reading time in minutes for posts
  showReadingTime = true

  # Show table of contents at the top of your posts (defaults to false)
  # Alternatively, add this param to post front matter for specific posts
  # toc = true

  # Show full page content in RSS feed items
  #(default is Description or Summary metadata in the front matter)
  # rssFullText = true

[languages]
  [languages.en]
    title = "lambdajunkie"
    copyright = "2021-2024"

    [languages.en.params]
        keywords = "lambdajunkie"
        homeSubtitle = "A blog on Lisp, FP and random ramblings"
        subtitle = "A blog on Lisp, FP and random ramblings"
        minuteReadingTime = "min read"
        # leave empty to disable, enter display text to enable
        # lastModDisplay = ""
        menuMore = "Show more"
        readMore = "Read more"
        readOtherPosts = "Read other posts"
        writtenBy = "Written by Ram Vedam"
        dateFormatSingle = "2006-01-02"
        dateFormatList = "2006-01-02"
        newerPosts = "Newer posts"
        olderPosts = "Older posts"
    [languages.en.params.logo]
      logoText = "lambdajunkie"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/rvedam"
      [[languages.en.menu.main]]
        identifier = "linkedin"
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/ramvedam/"
      [[languages.en.menu.main]]
        identifier = "twitter"
        name = "Twitter"
        url = "https://twitter.com/unxn3rd"

[params.utterances]
repository = "rvedam/rvedam.github.io"

# All comment utterance issues will be labeled based on og:title
issueTerm = "og:title"
theme = "github-dark"
